before_script:
  - source /etc/profile
  - apt -y update && apt -y upgrade
  - apt -y install python-pytest
stages:
  - build
  - test
run-build:
  stage: build
  script:
    - python setup.py --command-packages=stdeb.command  bdist_deb
  artifacts:
    paths:
    - deb_dist/python-mopidy-muzlab_*_all.deb
test:
  stage: test
  script:
   - dpkg -i deb_dist/python-mopidy-muzlab_*_all.deb
   - cd mopidy_muzlab; pytest -v
  after_script:
    - scp -P22022 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null deb_dist/python-mopidy-muzlab_*_all.deb repo@10.77.3.66:/home/repo/gitlab_packages/
