before_script:
  - source /etc/profile
stages:
  - build
run-build:
  stage: build
  script:
    - apt -y update && apt -y upgrade
    - python setup.py --command-packages=stdeb.command  bdist_deb
  artifacts:
    paths:
    - deb_dist/*

