sudo: required
dist: trusty

language: python

python:
  - "2.7_with_system_site_packages"

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y gir1.2-gst-plugins-base-1.0 gir1.2-gstreamer-1.0 python-gst-1.0"

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi"

notifications:
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
